
export const localTextDataGird = {
  columnMenuSortAsc: "Sắp xếp tăng dần",
  columnMenuSortDesc: "Sắp xếp giảm dần",
  columnMenuUnsort: "Bỏ sắp xếp",
  columnMenuHideColumn: "Ẩn cột",
  columnMenuManageColumns: "Quản lý cột",
  columnMenuFilter: "Tìm kiếm",
  filterPanelColumns: "Cột",
  filterPanelOperator: "Toán tử",
  filterPanelInputLabel: "Giá trị",
  filterOperatorContains: "Có chứa",
  filterOperatorEquals: "Bằng",
  filterOperatorStartsWith: "Bắt đầu bằng",
  filterOperatorEndsWith: "Kết thúc bằng",
  filterOperatorNot: "Không chứa",
  filterOperatorIsEmpty: "Giá trị trống",
  filterOperatorIsNotEmpty: "Giá trị không trống",
  filterOperatorIs: "Là",
  filterOperatorIsAnyOf: "Giá trị bất kỳ",
  filterPanelInputPlaceholder: "Tìm kiếm cột",
  columnsPanelHideAllButton: "Ẩn tất cả",
  columnsPanelShowAllButton: "Hiện tất cả",
  columnHeaderSortIconLabel: "Sắp xếp",
  columnHeaderFiltersLabel: "Tìm kiếm",
  columnMenuLabel: "Tùy chọn",
  columnsPanelTextFieldPlaceholder: "Tìm kiếm cột",
  columnsPanelTextFieldLabel: "Tìm kiếm cột",
  checkboxSelectionHeaderName: "Chọn tất cả",
  checkboxSelectionUnselectRow: "Bỏ chọn",
  footerRowSelected: (count: number) => `Đã chọn ${count} bản ghi`
};